#
# conductor:server - Netflix conductor server
#
FROM amazoncorretto:11

MAINTAINER Netflix OSS <conductor@netflix.com>

# Copy the project directly onto the image
COPY . /conductor
WORKDIR /conductor

# Build the server on run
ENTRYPOINT ./gradlew build -x test 
