on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK 11
        id: setup-java-11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Set up JDK 1.8
        id: setup-java-8
        uses: actions/setup-java@v1
        with:
          distribution: adopt
          java-version: 1.8
      - name: Run SonarScanner
        run: JAVA_HOME="${{ steps.setup-java-11.outputs.path }}" ./gradlew build sonarqube -x test -Dsonar.verbose=true -Dsonar.projectKey=conductor -Dsonar.host.url=https://sonarqube.dmlib.de -Dsonar.login=${{ secrets.DELUXE_ORG_SONAR_TOKEN }}
